package com.nightcatchers.core.domain.model

object MonsterArchetypeCatalog {

    val all: List<MonsterArchetype> = listOf(
        MonsterArchetype(
            id = "bed_lurker",
            number = 1,
            name = "Bed Lurker",
            subtitle = "The Under-Mattress Menace",
            emoji = "👾",
            rarity = Rarity.COMMON,
            spawnBias = SpawnBias("bedroom_floor", "night"),
            personality = Personality(
                core = "Shy and easily startled",
                loves = "Dusty corners and dark spaces",
                hates = "Bright lights and loud noises",
                catchphrase = "Shhh… I was here first!",
            ),
            defaultStats = PetStats(hunger = 70, happiness = 50, energy = 60, spookiness = 65, trust = 0),
            decayRates = DecayRates(hungerPerHour = 4, happinessPerHour = 3, energyPerHour = 2, spookinessPerHour = -1),
            favFood = "Dust Bunny Stew",
            favGame = "Hide and Peek",
            soothingAction = "Gentle humming",
        ),
        MonsterArchetype(
            id = "closet_creep",
            number = 2,
            name = "Closet Creep",
            subtitle = "The Wardrobe Wanderer",
            emoji = "🧟",
            rarity = Rarity.UNCOMMON,
            spawnBias = SpawnBias("closet", "night"),
            personality = Personality(
                core = "Dramatic and theatrical",
                loves = "Hanging clothes and cool breezes",
                hates = "Being seen mid-dramatic-pose",
                catchphrase = "You weren't supposed to open that!",
            ),
            defaultStats = PetStats(hunger = 60, happiness = 70, energy = 80, spookiness = 75, trust = 0),
            decayRates = DecayRates(hungerPerHour = 3, happinessPerHour = 5, energyPerHour = 3, spookinessPerHour = 2),
            favFood = "Shadow Soup",
            favGame = "Dress-Up Dash",
            soothingAction = "Storytelling",
        ),
        MonsterArchetype(
            id = "shadow_wisp",
            number = 3,
            name = "Shadow Wisp",
            subtitle = "The Flicker in the Corner",
            emoji = "🌫️",
            rarity = Rarity.RARE,
            spawnBias = SpawnBias("dark_corner", "any"),
            personality = Personality(
                core = "Curious and mischievous",
                loves = "Blinking lights and flickering candles",
                hates = "Complete stillness",
                catchphrase = "Did you see that? …No? Good.",
            ),
            defaultStats = PetStats(hunger = 50, happiness = 80, energy = 90, spookiness = 85, trust = 0),
            decayRates = DecayRates(hungerPerHour = 2, happinessPerHour = 4, energyPerHour = 5, spookinessPerHour = 3),
            favFood = "Moonbeam Mousse",
            favGame = "Shadow Puppet Show",
            soothingAction = "Soft lullaby",
        ),
        MonsterArchetype(
            id = "dust_bunny",
            number = 4,
            name = "Dust Bunny",
            subtitle = "The Fluff Under the Bed",
            emoji = "🐰",
            rarity = Rarity.COMMON,
            spawnBias = SpawnBias("under_furniture", "any"),
            personality = Personality(
                core = "Gentle and forgetful",
                loves = "Rolling into balls and collecting lint",
                hates = "Vacuums (obviously)",
                catchphrase = "Oh! Hello! I forgot you lived here.",
            ),
            defaultStats = PetStats(hunger = 80, happiness = 60, energy = 40, spookiness = 20, trust = 0),
            decayRates = DecayRates(hungerPerHour = 5, happinessPerHour = 2, energyPerHour = 1, spookinessPerHour = -2),
            favFood = "Fluffy Crumpets",
            favGame = "Roll Around",
            soothingAction = "Petting",
        ),
        MonsterArchetype(
            id = "sock_thief",
            number = 5,
            name = "Sock Thief",
            subtitle = "The Laundry Bandit",
            emoji = "🧦",
            rarity = Rarity.COMMON,
            spawnBias = SpawnBias("laundry_area", "any"),
            personality = Personality(
                core = "Cheeky and proud",
                loves = "Mismatched socks and warm dryers",
                hates = "Organised sock drawers",
                catchphrase = "You can't prove anything.",
            ),
            defaultStats = PetStats(hunger = 65, happiness = 75, energy = 85, spookiness = 30, trust = 0),
            decayRates = DecayRates(hungerPerHour = 3, happinessPerHour = 4, energyPerHour = 4, spookinessPerHour = 1),
            favFood = "Static Snacks",
            favGame = "Sock Sorting Sprint",
            soothingAction = "Offering socks back",
        ),
        MonsterArchetype(
            id = "door_rattler",
            number = 6,
            name = "Door Rattler",
            subtitle = "The Hallway Haunter",
            emoji = "🚪",
            rarity = Rarity.UNCOMMON,
            spawnBias = SpawnBias("hallway", "night"),
            personality = Personality(
                core = "Anxious but well-meaning",
                loves = "Squeaky hinges and draughts",
                hates = "Deadbolts",
                catchphrase = "I just wanted to check on you!",
            ),
            defaultStats = PetStats(hunger = 55, happiness = 55, energy = 70, spookiness = 60, trust = 0),
            decayRates = DecayRates(hungerPerHour = 3, happinessPerHour = 3, energyPerHour = 3, spookinessPerHour = 2),
            favFood = "Creak Crackers",
            favGame = "Knock Knock",
            soothingAction = "Reassurance",
        ),
        MonsterArchetype(
            id = "mattress_mole",
            number = 7,
            name = "Mattress Mole",
            subtitle = "The Spring Saboteur",
            emoji = "🦔",
            rarity = Rarity.RARE,
            spawnBias = SpawnBias("mattress", "sleep_time"),
            personality = Personality(
                core = "Industrious and tunnel-obsessed",
                loves = "Box springs and coil mazes",
                hates = "Memory foam (no tunnels!)",
                catchphrase = "I'm improving your lumbar support.",
            ),
            defaultStats = PetStats(hunger = 75, happiness = 50, energy = 65, spookiness = 45, trust = 0),
            decayRates = DecayRates(hungerPerHour = 5, happinessPerHour = 2, energyPerHour = 3, spookinessPerHour = 1),
            favFood = "Spring Roll",
            favGame = "Tunnel Dig",
            soothingAction = "Singing a work song",
        ),
        MonsterArchetype(
            id = "mirror_phantom",
            number = 8,
            name = "Mirror Phantom",
            subtitle = "The Reflection That Lingers",
            emoji = "🪞",
            rarity = Rarity.LEGENDARY,
            spawnBias = SpawnBias("mirror_surface", "night"),
            personality = Personality(
                core = "Wise and enigmatic",
                loves = "Candlelight reflections and riddles",
                hates = "Broken mirrors (bad luck for everyone)",
                catchphrase = "You look… different in here.",
            ),
            defaultStats = PetStats(hunger = 40, happiness = 90, energy = 80, spookiness = 95, trust = 0),
            decayRates = DecayRates(hungerPerHour = 1, happinessPerHour = 2, energyPerHour = 2, spookinessPerHour = 4),
            favFood = "Starlight Sorbet",
            favGame = "Mirror Mirror",
            soothingAction = "Telling a riddle",
        ),
        MonsterArchetype(
            id = "pillow_poltergeist",
            number = 9,
            name = "Pillow Poltergeist",
            subtitle = "The Nightly Fluff Disturber",
            emoji = "🛏️",
            rarity = Rarity.COMMON,
            spawnBias = SpawnBias("pillow", "sleep_time"),
            personality = Personality(
                core = "Well-intentioned but clumsy",
                loves = "Fluffing and re-arranging",
                hates = "Flat pillows",
                catchphrase = "I was just trying to help you sleep!",
            ),
            defaultStats = PetStats(hunger = 70, happiness = 65, energy = 55, spookiness = 35, trust = 0),
            decayRates = DecayRates(hungerPerHour = 4, happinessPerHour = 3, energyPerHour = 2, spookinessPerHour = -1),
            favFood = "Cloudberry Cream",
            favGame = "Pillow Fluffathon",
            soothingAction = "Staying still",
        ),
        MonsterArchetype(
            id = "drain_sprite",
            number = 10,
            name = "Drain Sprite",
            subtitle = "The Bathroom Bather",
            emoji = "🌀",
            rarity = Rarity.UNCOMMON,
            spawnBias = SpawnBias("bathroom_drain", "any"),
            personality = Personality(
                core = "Bubbly and soapy",
                loves = "Warm steam and spirals",
                hates = "Dry environments",
                catchphrase = "Gurgle gurgle!",
            ),
            defaultStats = PetStats(hunger = 60, happiness = 70, energy = 75, spookiness = 40, trust = 0),
            decayRates = DecayRates(hungerPerHour = 3, happinessPerHour = 4, energyPerHour = 3, spookinessPerHour = 1),
            favFood = "Bubble Tea",
            favGame = "Whirlpool Spin",
            soothingAction = "Running warm water",
        ),
        MonsterArchetype(
            id = "attic_howler",
            number = 11,
            name = "Attic Howler",
            subtitle = "The Rafter Roamer",
            emoji = "🦉",
            rarity = Rarity.LEGENDARY,
            spawnBias = SpawnBias("ceiling", "night"),
            personality = Personality(
                core = "Ancient and melancholy",
                loves = "Old boxes and forgotten toys",
                hates = "When old things are thrown away",
                catchphrase = "I remember when this house was young…",
            ),
            defaultStats = PetStats(hunger = 30, happiness = 45, energy = 60, spookiness = 90, trust = 0),
            decayRates = DecayRates(hungerPerHour = 1, happinessPerHour = 3, energyPerHour = 2, spookinessPerHour = 3),
            favFood = "Nostalgia Biscuits",
            favGame = "Memory Lane",
            soothingAction = "Sharing a memory",
        ),
    )

    fun findById(id: String): MonsterArchetype? = all.find { it.id == id }
}
